<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>nmap</p>

<p>This page is located at <code>views/index/index.phtml</code></p>


<?php echo \Phalcon\Tag::form(array("nmap/result", "autocomplete" => "off")) ?>  
            <?php echo \Phalcon\Tag::textField(array("name", "size" => 30)) ?> 

            <?php echo \Phalcon\Tag::textField(array("slug", "size" => 30)) ?> 

      <?php echo \Phalcon\Tag::submitButton(array("Save", "class" => "btn")) ?>

   </table> 
</form>