<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>nmap</p>

<p>This page is located at <code>views/index/index.phtml</code></p>
  <table>
    <div class="forminput">Target:
       <?php echo \Phalcon\Tag::textField(array("myText1", "size" => 30,"value" => "127.0.0.1" ,"placeholder"=>"Target")) ?> 
    </div>
    <div class="forminput">Options:
       <?php echo \Phalcon\Tag::textField(array("myText2", "size" => 30,"value" => "-T4 -v -A" ,"placeholder"=>"Command")) ?> 
    </div>
    <div class="forminput">Command:
       <?php echo \Phalcon\Tag::textField(array("Command", "size" => 30,"value" => "nmap" ,"placeholder"=>"Target")) ?> 
    </div>
    <div class="forminput">
        <?php echo \Phalcon\Tag::submitButton(array("button", "onclick"=>"test()" )) ?> 
    </div>      
    </table>     
<div id="loader"></div>
<div id="content"></div>
<script>
   function test(){
    var trgt = $('#Command');
    $.ajax({
        url: "nmap/scan",
        type: "post",
        data: trgt,
        async: true,
        timeout: 0,
        beforeSend: function(){
            document.getElementById("loader").style.display = "block";
            $("#content").html("Processing...");

        },
        success: function(result){
            document.getElementById("loader").style.display = "none";
            $("#content").html(result);
        }, 
    });
   }
</script>


