<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>nmap</p>

<p>This page is located at <code>views/index/index.phtml</code></p>


            <!-- <?php echo \Phalcon\Tag::textField(array("nmapdetail", "size" => 30,"value" => "test")) ?>  -->
            <?php echo \Phalcon\Tag::textField(array("nmaptarget", "size" => 30,"value" => "")) ?> 
<button onclick="test()">button</button>
<div id="content"></div>


<script>

   function test(){
    $.ajax({
        url: "nmap/scan",
        async: true,
        timeout: 0,
        success: function(result){
            $("#content").html(result);
        },
        
    });
   }
</script>


